### ISSUE TITLE
Support for Ubuntu 16.04

### ISSUE THREAD

**Issue by PascalAnimateur** [opendevshop/ansible-role-aegir-apache#1]
When installing in 16.04, ansible can't find libapache2-mod-php5 ... this package has been renamed to libapache2-mod-php in that version.

Is there a way to detect the environment so ansible looks for the correct package?

**Comment by jonpugh** [comment]
Sorry for the very late reply. 

We've supported Ubuntu 16 for some time.

Thanks.
